-- 코드를 입력하세요

SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO, REST_REVIEW AS REVIEW
WHERE INFO.REST_ID = REVIEW.REST_ID AND INFO.ADDRESS LIKE '서울%'
GROUP BY ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;
